<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC (c) 2004-2019
 *
 * Generated from /home/edsel/git/biz.jmaconsulting.waitlisttickets/xml/schema/CRM/Waitlisttickets/WaitListTickets.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:2f4bb961d457ad208a88b5dc36306ed6)
 */

/**
 * Database access object for the WaitListTickets entity.
 */
class CRM_Waitlisttickets_DAO_WaitListTickets extends CRM_Core_DAO {

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_wait_list_tickets';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique WaitListTickets ID
   *
   * @var int
   */
  public $id;

  /**
   * FK to Event
   *
   * @var int
   */
  public $event_id;

  /**
   * FK to Participant
   *
   * @var int
   */
  public $participant_id;

  /**
   * FK to Price Field
   *
   * @var int
   */
  public $price_field_id;

  /**
   * FK to Price Field Value
   *
   * @var int
   */
  public $price_field_value_id;

  /**
   * Number of tickets required
   *
   * @var int
   */
  public $qty;

  /**
   * Number of participants
   *
   * @var int
   */
  public $participant_count;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_wait_list_tickets';
    parent::__construct();
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'event_id', 'civicrm_event', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'participant_id', 'civicrm_participant', 'id');
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'price_field_id', 'civicrm_price_field_value', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('Unique WaitListTickets ID'),
          'required' => TRUE,
          'where' => 'civicrm_wait_list_tickets.id',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
        'event_id' => [
          'name' => 'event_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('FK to Event'),
          'where' => 'civicrm_wait_list_tickets.event_id',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
        'participant_id' => [
          'name' => 'participant_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('FK to Participant'),
          'where' => 'civicrm_wait_list_tickets.participant_id',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
        'price_field_id' => [
          'name' => 'price_field_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('FK to Price Field'),
          'where' => 'civicrm_wait_list_tickets.price_field_id',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
        'price_field_value_id' => [
          'name' => 'price_field_value_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('FK to Price Field Value'),
          'where' => 'civicrm_wait_list_tickets.price_field_value_id',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
        'qty' => [
          'name' => 'qty',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Waitlisttickets_ExtensionUtil::ts('Qty'),
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('Number of tickets required'),
          'where' => 'civicrm_wait_list_tickets.qty',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
        'participant_count' => [
          'name' => 'participant_count',
          'type' => CRM_Utils_Type::T_INT,
          'title' => CRM_Waitlisttickets_ExtensionUtil::ts('Participant Count'),
          'description' => CRM_Waitlisttickets_ExtensionUtil::ts('Number of participants'),
          'where' => 'civicrm_wait_list_tickets.participant_count',
          'table_name' => 'civicrm_wait_list_tickets',
          'entity' => 'WaitListTickets',
          'bao' => 'CRM_Waitlisttickets_DAO_WaitListTickets',
          'localizable' => 0,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'wait_list_tickets', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'wait_list_tickets', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
